# Netlify configuration file

[build]
  # Directory to publish (relative to root of your repo)
  publish = "dist"
  # Default build command
  command = "npm run build"

# Redirects and headers
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for JavaScript and CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for fonts
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache headers for HTML - shorter cache time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variable configuration
[build.environment]
  # Set Node version
  NODE_VERSION = "20.11.1"

# Production context: all deploys from the Production branch set in your site's
# deploy contexts will inherit these settings.
[context.production.environment]
  # Production specific environment variables
  VITE_APP_ENVIRONMENT = "production"

# Deploy Preview context: all deploys generated from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  VITE_APP_ENVIRONMENT = "preview"

# Branch Deploy context: all deploys that are not from a pull/merge request or
# from the Production branch will inherit these settings.
[context.branch-deploy.environment]
  VITE_APP_ENVIRONMENT = "development"

# Enable Brotli compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true