default_platform(:android)

platform :android do
  desc "Deploy to Google Play Store"
  lane :deploy do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "../"
    )
    
    upload_to_play_store(
      track: 'internal',
      aab: '../app/build/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['GOOGLE_PLAY_SERVICE_ACCOUNT']
    )
  end
  
  desc "Build signed AAB"
  lane :build do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "../"
    )
  end
end